name: 'ci-action'
description: 'Continious Integration action for go- and node- projects'
inputs:
  organization:
    description: The name of the organization(s) on GitHub containing private repositories (comma separated)
    default: untillpro
  token:
    description: Auth token used to fetch dependencies from private repositories
  codecov-token: # deprecated
    description: Codecov token
  codecov-go-race: # deprecated
    description: 'Codecov: use Go Race Detector'
    default: 'true'
  ignore-build: # deprecated
    description: 'Ignores go build'
    default: 'false'
  publish-keep:
    description: Number of kept releases (0 - all)
    default: 8
  repository:
    description: 'Repository name with owner. For example, untillpro/ci-action'
    default: ${{ github.repository }}
  run-mod-tidy:
    description: 'Only for go-projects: execute `go mod tidy`'
    default: 'true'
  main-branch:
    description: Main branch name
    default: main
  ignore-copyright: # deprecated
    description: 'Do not check the copyright in first comments of source code'
    default: 'false'
  test-folder:
    description: 'Test only in passed folder'
    default: ''
  short-test:
    description: 'Test onlywith flag -short'
    default: 'false'
  stop-test:
    description: 'Does not make test'
    default: 'false'
  build-cmd:
    description: 'command to makke build'
    default: ''
  extra_env:
    default: ''
outputs:
  release_id:
    description: 'The ID of the created Release'
  release_name:
    description: 'The name (version) of the created Release'
  release_html_url:
    description: 'The URL users can navigate to in order to view the release'
  release_upload_url:
    description: 'The URL for uploading assets to the release'
  asset_browser_download_url:
    description: 'The URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'composite'
  steps:
    - name: Run CI
      shell: bash
      env:
        INPUT_ORGANIZATION: ${{ inputs.organization }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_CODECOV_TOKEN: ${{ inputs.codecov-token }} # deprecated
        INPUT_CODECOV_GO_RACE: ${{ inputs.codecov-go-race }} # deprecated
        INPUT_PUBLISH_KEEP: ${{ inputs.publish-keep }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_RUN_MOD_TIDY: ${{ inputs.run-mod-tidy }}
        INPUT_MAIN_BRANCH: ${{ inputs.main-branch }}
        INPUT_TEST_FOLDER: ${{ inputs.test-folder }}
        INPUT_SHORT_TEST: ${{ inputs.short-test }}
        INPUT_BUILD_CMD: ${{ inputs.build-cmd }}
        INPUT_EXTRA_ENV: ${{ inputs.extra_env }}
      run: |
        bash ${{ github.action_path }}/scripts/ci_main.sh
