name: Checkout (if not yet) and Setup Go
description: Checkout repository if not checked out yet and install Go with version based on go.work/go.mod

inputs:
  fetch_depth:
    description: Fetch depth for checkout
    required: false
    default: 1
  ref:
    description: "Git ref to checkout; defaults to github.ref when not set"
    required: false
  token:
    description: "Token for checkout; defaults to GITHUB_TOKEN when not set"
    required: false
  submodules:
    description: "Submodules option for actions/checkout@v4 (for example: recursive)"
    required: false
  path:
    description: "Path to checkout the repository into (relative to $GITHUB_WORKSPACE)"
    required: false
    default: "."
  go-version:
    # Need for repositories that contain few languages, e.g. air-devops. Language can not be detected for abomber
    description: "Go version to use; if not specified, version will be detected from go.work/go.mod"
    required: false

outputs:
  go-version:
    description: Go version being used (either specified or detected)
    value: ${{ inputs.go-version || steps.detect-go.outputs.go-version }}

runs:
  using: composite
  steps:
    - name: Checkout (if not yet)
      uses: actions/checkout@v5
      if: ${{ hashFiles('.git/HEAD') == '' }} # checkout only if not checked out yet
      with:
        token: ${{ inputs.token || github.token }}
        # note: both pull_request_target and pull_request events are needed to make check_copyright.sh work properly
        ref: ${{ inputs.ref || ((github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.event.pull_request.head.sha || github.sha) }}
        submodules: ${{ inputs.submodules }}
        path: ${{ inputs.path }}

    - name: Detect Go version
      id: detect-go
      if: ${{ !inputs.go-version }}
      shell: bash
      run: bash "$GITHUB_ACTION_PATH/../scripts/detect-go-version.sh"

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version || steps.detect-go.outputs.go-version }}
        cache: true
