name: Checkout and Setup Go
description: Checkout repository and install Go based on go.work/go.mod

inputs:
  fetch_depth:
    description: Fetch depth for checkout
    required: false
    default: 1
  token:
    description: 'Token for checkout; defaults to GITHUB_TOKEN when not set'
    required: false
  submodules:
    description: 'Submodules option for actions/checkout@v4 (for example: recursive)'
    required: false
  path:
    description: 'Path to checkout the repository into (relative to $GITHUB_WORKSPACE)'
    required: false
    default: '.'

outputs:
  go-version:
    description: Detected Go version
    value: ${{ steps.detect-go.outputs.go-version }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ inputs.token || github.token }}
        fetch-depth: ${{ inputs.fetch_depth }}
        submodules: ${{ inputs.submodules }}
        path: ${{ inputs.path }}

    - name: Detect Go version
      id: detect-go
      shell: bash
      run: bash "$GITHUB_ACTION_PATH/../scripts/detect-go-version.sh"

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.detect-go.outputs.go-version }}
        cache: true

